FROM ubuntu:14.04
MAINTAINER Michalis Lazaridis <Michalis.Lazaridis@iti.gr>
RUN apt-get update \
#  && apt-get upgrade -y \
  && apt-get install -y \
  default-jdk \
  python-numpy \
  python-pip \
  && \
  apt-get clean
RUN pip install web.py
RUN mkdir -p /crawler/lib
RUN mkdir -p /crawler/images
COPY ./dist/ /crawler/
COPY ./lib/ /crawler/lib/
COPY ./run_service.py /crawler/
#ENV CLASSPATH .:/crawler/lib/
#ADD flickr.tar.gz ./
#CMD python /crawler/run_service.py 9876
